# Generated by Django 3.2.4 on 2021-07-07 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('idConcepto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreConcepto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('autor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('historia', models.CharField(max_length=50)),
                ('tecnica', models.CharField(max_length=50)),
                ('precio', models.IntegerField(max_length=50)),
                ('imagen', models.CharField(max_length=500)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concepto')),
            ],
        ),
    ]
